### ISSUE TITLE
Ready to release?

### ISSUE THREAD

**Issue by ocharles** [TristanCacqueray/ki-effectful#5]
Hi @TristanCacqueray. This library looks very interesting - what's the status of it? Do you plan to release it to Hackage?

**Comment by TristanCacqueray** [comment]
I haven't found a use for it yet, my main ki-powered application is still just a Reader. My only concern is that the Scope is presently hidden, and entering an existing scope requires using the `withCurrentScope` trampoline, which looks like a bit too complicated.

That being said, this library is probably already hackage-worthy, and I'd be happy to make a release.

**Comment by TristanCacqueray** [comment]
The current version is now available at https://hackage.haskell.org/package/ki-effectful-0.1.0.0 .

Then about my concern above, it seems like we could simply add:
```haskell
askScope :: StructuredConcurrency :> es => Eff es Scope
enterScope :: StructuredConcurrency :> es => Scope -> Eff es a -> Eff es a
```

**Comment by ocharles** [comment]
Thanks @TristanCacqueray! I think we can close this, great work! I'm still not quite using this (I haven't quite worked out if we want to move to `effectful` yet)
