### ISSUE TITLE
Suggestion: make `Scope` an explicit argument

### ISSUE THREAD

**Issue by mitchellwrosen** [TristanCacqueray/ki-effectful#6]
Hey!

I'd like to suggest a change to the API, or at least point out one motivation for having an explicit scope object even when operating in a reader-like monad that can pass it along implicitly.

A big advantage of an explicit scope object is to be able to read the structure of the concurrency off of the page.

```haskell
Ki.scoped \scope -> do
  _ <- Ki.fork scope worker1
  _ <- Ki.fork scope worker2
  Ki.awaitAll
```

Here, I can see that this scope contains _only_ `worker1` and `worker2`, which is important because the siblings are all related to each other. An exception in any brings the whole lot down.

It's precisely why I'd advise against writing code that passes a scope down into some custom helper function like:

```haskell
Ki.scoped \scope -> do
  someHelperFunction scope
  someMoreStuff
```

What's `someHelperFunction` doing with the scope? Forking some threads into it and possibly passing it down into another helper? We'll have to jump around to find out.

And by the same logic, with an implicit scope, you cannot just read code like

```haskell
import Effectful.Ki as Ki

Ki.scoped do
  _ <- Ki.fork worker1
  _ <- Ki.fork worker2
  Ki.atomically Ki.awaitAll
```

and be confident that `worker1` and `worker2` are the only threads related to each other, because `worker1` could go off and spawn more siblings into the _same_ scope!

```haskell
worker1 = do
  Ki.fork moreSiblings
  Ki.fork evenMoreSiblings
```

There's a cost to the explicit scope design of course: it's syntactically noisier. So, some users might prefer the implicit style, despite the aforementioned downsides. I just thought the downsides are worth pointing out, as they aren't necessarily obvious.

**Comment by TristanCacqueray** [comment]
Hey! This issue is like the opposite of #1 :)

To prevent `worker1` from spawning more siblings, it seems like we would need a way to ensure a given `es` type variable doesn't have the `StructuredConcurrency` constraint. I don't know if that is even possible. In any case, I agree with you, the syntax gain isn't worth the aforementioned downside. Moreover, your suggestion match what I commented on #5.

Thank you for the opening this issue, I'll restore the initial api shortly.

**Comment by ocharles** [comment]
This is really interesting! @mitchellwrosen it might be worth documenting this design pattern/idea somewhere - I'd love to discuss it more. Maybe a discussion on the Ki GitHub project?

**Comment by mitchellwrosen** [comment]
Sure!
